FROM scireum/s3-ninja:6.4 

USER sirius

# Inclua todos os buckets que precisa no comando a seguir

CMD mkdir -p /home/sirius/data/dental_college_1 && \
    mkdir -p /home/sirius/data/dental_college_2 && \
    /home/sirius/run.sh